---
## Sequences Processing & Negative control ## 
rnacentral_coords: "data/raw/rnacentral-GRCh38-coords.bed"
rnacentral_lncrna_seqs: "data/raw/rnacentral-lncrna-seq.csv"
rnacentral_short_ncrna_seqs: "data/raw/rnacentral-short-ncrna-seq.csv"
rnacentral_pre_mirna_seqs: "data/raw/rnacentral-pre-mirna-seq.csv"
genome_annotations: "data/raw/GRCh38_p14_genomic.gff"
genome_seq: "data/raw/hg38.p14.fa"
protein_coding_refseq: "data/raw/hgnc-protein-coding-RefSeq.txt"
gencode_bed: "data/raw/gencode-annotation.bed" 
genes_complement: "data/raw/genes-complement"

## Conservation features ##
bigWigSummary_exe: "bin/bigWigSummary"
_100w_phyloP_bw: "data/raw/hg38.phyloP100way.bw"
zoonomia_phyloP_bw: "data/raw/hg38.phyloP241mammalian2020v2.bigWig"
gerp_bw_mammals: "data/raw/gerp_91mammals_conservation_scores.homo_sapiens.GRCh38.bw"
gerp_bw_amniontes: "data/raw/gerp_63amniotes_conservation_scores.homo_sapiens.GRCh38.bw"

## Transcriptome expression features ##
encode_folder: "/Volumes/archive/userdata/student_users/danielaschiavinato/dani-scratch/features-of-function-data/ENCODE"
# Note: Each sample type should have its own folder within the ENCODE folder. Ex: encode_folder/primary-cell; encode_folder/tissue

## Genomic repeats associated features ## 
human_genome_mmseqs: "data/raw/mmseqs/human_genome"
dfam_hits: "data/raw/dfam-hg38-sorted.bed"

## Protein-and-specific-rna-features ##
interaction_database: "data/raw/curated-interaction-database.fa"
bigBedToBed_exe: "bin/bigBedToBed"

## Population variation features ## 
gnomad_directory: "data/raw/gnomad"

## Epigenetic features ##
histone_marks_directory: "data/epigenetic_data/histone_marks"
chromatin_accessibility_directory: "data/epigenetic_data/chromatin_accessibility"
methylome_directory: "data/epigenetic_data/methylome"

gencode_annotations: "data/raw/gencode.v45.annotation.gtf"
... 