# Author: Daniela Schiavinato
#### Horizontal barplots ######

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from pandas.plotting import parallel_coordinates
from datetime import datetime
date = datetime.now().strftime('%Y%m%d')

# Set the color palette for the groups
custom_palette = {
	'Random':'grey',		
	'Intrinsic':'goldenrod',	 
	'Conservation':'orangered',  
	'Transcription':'forestgreen',				
	'Epigenetic':'deepskyblue',		
	'Coding/Structure':'royalblue',	  
	'Repeats':'darkorange',	   
	'Population':'hotpink'	 
}

feature_to_group = {
	'Tissue RPKM': 'Transcription',
	'Primary cell RPKM': 'Transcription',
	'PhyloP-mammals': 'Conservation',
	'PhyloP-vertebrates': 'Conservation',
	'GERP-mammals': 'Conservation',
	'H3K79me2': 'Epigenetic',
	'H3K79me1': 'Epigenetic',
	'Copies': 'Repeats',
	'MaxEnt splicing': 'Coding/Structure', 
	'RNAcode': 'Coding/Structure',
	'GERP-vertebrates': 'Conservation',
	'Covariance': 'Coding/Structure',
	'H3K9ac': 'Epigenetic',
	'Chromatin acc': 'Epigenetic',
	'GC%': 'Intrinsic',
	'CpG': 'Intrinsic',
	'TA': 'Intrinsic',
	'AC': 'Intrinsic',
	'CC': 'Intrinsic',
	'GA': 'Intrinsic',
	'T%': 'Intrinsic',
	'G%': 'Intrinsic',
	'C%': 'Intrinsic',
	'MFE': 'Coding/Structure',
	'Interactions': 'Coding/Structure',
	'Methylome': 'Epigenetic',
	'Repeat free': 'Repeats',
	'Fickett': 'Coding/Structure',
	'GG': 'Intrinsic',
	'Low complexity': 'Intrinsic',
	'GT': 'Intrinsic',
	'SNPs': 'Population',
	'MAF': 'Population',
	'Random': 'Random'
}

rna_types = ['mrna', 'sncrna', 'lncrna', 'allrna']

for rna in rna_types:
	df = pd.read_csv(f"./results/20251207-ks_statistics_{rna}.csv")
	df = df.sort_values(by='ks', ascending=False)
	df['Group'] = df['feature'].map(feature_to_group)
	# Get the explicit order of features after sorting, to ensure seaborn uses this exact order
	feature_order = df['feature'].tolist()
	# Create the plot
	plt.figure(figsize=(8, 10))
	# Pass the 'order' parameter to sns.barplot to control the y-axis category order
	ax = sns.barplot(x='ks', y='feature', data=df, hue='Group', dodge=False, palette=custom_palette, order=feature_order, legend=False)
	# Add error bars
	# Iterate through the features in the defined order to correctly align error bars
	for i, feature_name in enumerate(feature_order):
		# Find the corresponding row in the DataFrame for the current feature
		row = df[df['feature'] == feature_name].iloc[0]
		bar_x = row['ks']
		# Calculate the absolute difference for lower and upper errors
		lower = abs(row['ks'] - row['ks_lower'])
		upper = abs(row['ks_upper'] - row['ks'])
		# The y-position for the i-th feature in the ordered list is simply its numerical index 'i'
		# on the categorical y-axis generated by seaborn.
		center_y = i
		plt.errorbar(
			x=np.array([bar_x]),
			y=np.array([center_y]),
			xerr=np.array([[lower], [upper]]),
			fmt='none', # 'none' means no connecting line/marker
			capsize=3,  # Size of the error bar caps
			color='black',
			linewidth=1.5
		)
	plt.xlim(0, 0.9) 
	# Set plot labels and title
	plt.yticks(fontsize=19)
	plt.xticks(fontsize=18)
	plt.xlabel('KS-statistic', fontsize=20)
	plt.title(rna.replace("rna", "RNA"), fontsize=30)
	#plt.legend(title='Feature group', bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=18)
	plt.tight_layout()
	plt.savefig(f"./results/plots/feature_comparison_{rna}_{date}.png", dpi=600, bbox_inches='tight')





######### KS distribution Figure ############ 
# features = [
	'Random', 'GT','Low complexity','GA','CpG','GC%','TA',
	'SNPs','MAF','Repeat free','Copies', 'Interactions','MFE',
	'Fickett','RNAcode', 'Covariance','Methylome', 'Chromatin acc', 'H3K9ac', 'H3K79me1', 'H3K79me2',
	'GERP-vertebrates','GERP-mammals','PhyloP-vertebrates','PhyloP-mammals',
	'Primary cell RPKM','Tissue RPKM']

features = [
	'Random', 'Tissue RPKM', 'Primary cell RPKM', 'PhyloP-mammals', 'PhyloP-vertebrates',
	'GERP-mammals', 'GERP-vertebrates', 'H3K79me2', 'H3K79me1', 'H3K9ac', 'Chromatin acc',
	'Methylome', 'MaxEnt splicing', 'Covariance', 'RNAcode', 'Fickett', 'MFE', 'Interactions', 'Copies',
	'Repeat free', 'MAF', 'SNPs', 'G%', 'T%', 'GC%', 'CpG', 'TA', 'GA', 'Low complexity', 'C%', 'GT']



file_path = './results/20251206-ks-for-plot.csv'  
df = pd.read_csv(file_path)

#df = df.drop(columns=['all', 'all_upper', 'all_lower']) # Added manually afterwards as a horizontal line 

# Melt the DataFrame to long format for KS-statistic values
df_melted = pd.melt(df, id_vars=['feature'], 
					value_vars=['mRNA', 'sncRNA', 'lncRNA'], 
					var_name='Dataset', value_name='KS-statistic')

# Melt for upper confidence intervals
df_upper = pd.melt(df, id_vars=['feature'], 
				   value_vars=['mRNA_upper', 'sncRNA_upper', 'lncRNA_upper'], 
				   var_name='Dataset', value_name='KS-statistic_upper')

# Melt for lower confidence intervals
df_lower = pd.melt(df, id_vars=['feature'], 
				   value_vars=['mRNA_lower', 'sncRNA_lower', 'lncRNA_lower'], 
				   var_name='Dataset', value_name='KS-statistic_lower')

# Remove '_upper' and '_lower' from Dataset names for merging
df_upper['Dataset'] = df_upper['Dataset'].str.replace('_upper', '')
df_lower['Dataset'] = df_lower['Dataset'].str.replace('_lower', '')

# Merge upper and lower confidence intervals with the main DataFrame
df_melted = df_melted.merge(df_upper, on=['feature', 'Dataset'], how='left')
df_melted = df_melted.merge(df_lower, on=['feature', 'Dataset'], how='left')

df_melted['feature'] = pd.Categorical(df_melted['feature'], categories=features, ordered=True) 
df_melted = df_melted.sort_values('feature')

# Create scatter plot
plt.figure(figsize=(16, 8))
ax = sns.scatterplot(data=df_melted, x='feature', y='KS-statistic', hue='Dataset', style='Dataset', s=200, legend=True)

for i in range(len(df_melted)):
	lower = abs(df_melted['KS-statistic'][i] - df_melted['KS-statistic_lower'][i])
	upper = abs(df_melted['KS-statistic_upper'][i] - df_melted['KS-statistic'][i])
	
	plt.errorbar(
		x=df_melted['feature'][i],
		y=df_melted['KS-statistic'][i],
		yerr=[[lower], [upper]],  # nested list for asymmetric error bars
		fmt='none',
		capsize=4,
		color='black',
		linewidth=1.5,
		alpha=0.8
	)

ax.axhline(y=0.02, color='red', linestyle='--', linewidth=1)  # Customize color, linestyle, and linewidth

ax.yaxis.grid(True, linestyle='--', linewidth=0.5, color='gray', alpha=0.7)  # Horizontal grid lines
ax.xaxis.grid(True, linestyle='--', linewidth=0.5, color='gray', alpha=0.7) 
ticks = ax.get_xticks()
ax.set_xticks(ticks + 0.1)   # shift right by 0.1 units
# Rotate x-axis labels for better readability
plt.xticks(rotation=45, fontsize=20, ha='right', rotation_mode='anchor')
plt.yticks(fontsize=20)
plt.xlabel('Feature', fontsize=20)
plt.ylabel('KS-statistic', fontsize=20)
plt.legend(fontsize=20)
#ax.set_xlim(-0.5, 8.5)

# Set labels and title
plt.title('Kolmogorov-Smirnov statistic by feature and dataset', fontsize=25)
plt.savefig('./results/plots/ks-plot-20260612', dpi=600, bbox_inches='tight') 






